# Generated by Django 4.0 on 2021-12-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
