# Generated by Django 4.0 on 2022-01-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoshop', '0003_items_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='username',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='username',
            field=models.CharField(default='vaibhav', max_length=20),
            preserve_default=False,
        ),
    ]
